apiVersion: v2
name: cloud-edge
description: A Helm chart for Cloudâ€‘Edge ROS 2 deployment (fleet manager in cloud, processing at edge)
type: application
version: 0.1.1
appVersion: humble
keywords:
  - ros2
  - cloud
  - edge
maintainers:
  - name: Miguel-Angel-Mateo-Casali
    email: mmateo@cigip.upv.es